import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/server/navbar/Navbar";
import { lato, poppins } from "./fonts";
import LeftCard from "@/components/server/LeftCard";
import { ProjectsProvider } from "@/context/projectProvider";
import Template from "./template";
import AuthProvider from "@/context/AuthProvider";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${poppins.variable} ${lato.variable}`}>
      <body
        suppressHydrationWarning={true}
        className='min-w-[320px] overflow-auto'
      >
        <AuthProvider>
          <div>
            <ProjectsProvider>
              <Navbar />

              <div className='border-4 border-black bg-primary min-h-lvh'>
                <div className='min-[450px]:w-[95%] w-full md:w-[90%] mx-auto grid grid-cols-12 gap-5 border-2 font-poppin  border-black p-2 min-[450px]:p-5'>
                  <div className='lg:col-span-3 sm:col-span-4 col-span-full'>
                    <LeftCard />
                  </div>
                  <div className='lg:col-span-9 sm:col-span-8 col-span-full bg-slate-800/20 rounded-2xl text-typography p-3 space-y-8 shadow-2xl '>
                    <Template>{children}</Template>
                  </div>
                </div>
              </div>
            </ProjectsProvider>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
